### PR TITLE
Set up AppImage build

### PR DESCRIPTION
**Pull request by TheAssassin**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.
If you would like to see only one entry for the Pull Request in your project's history, then please enable [this GitHub functionality](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/) on your repo. It allows you to squash (combine) the commits when merging.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by TheAssassin** [comment]
P.S.: In PRs, AppImages are built and uploaded temporarily to https://transfer.sh, which works for this PR already. You can find the URLs in the build log.

**Comment by probonopd** [comment]
Thanks a lot @TheAssassin - makes it so much easier to get and run inspectrum on Linux!

**Comment by miek** [comment]
First off, I appreciate the contribution, thank you.

However, this isn't something I'm interested in personally and I'm not keen on maintaining it, or recommending it as an official option as I'd be unable to support it. So unfortunately I won't be merging this, I hope you understand.

**Comment by TheAssassin** [comment]
I'm a bit disappointed. Considering the few lines of code I added to the Travis CI config, it doesn't seem to add a lot of overhead. And you give Linux users an opportunity to run the app with zero effort.

But you should consider merging the PR partially, then. The changes I made to the build configuration (creating/installing a desktop file and (placeholder) icon, that is) are really important, and nothing that'd require any real maintenance work, actually it improves the installation of your app a lot.

Furthermore, the changes in the Travis file regarding the installation and use of the libraries you need to build yourself actually fix the wrong use of the build prefix.

You see, the majority of this isn't directly AppImage related, and should be worth merging.

**Comment by probonopd** [comment]
@miek to normal users, source code without binaries is useless...

**Pull request closed without merging**
