### PR TITLE
Clear SigMF annotations on new file load

### PR DESCRIPTION
**Pull request by devnulling**
When a new file is loaded, the annotations qlist is not cleared, this PR fixes that.

### CODE REVIEW

**Review by jacobagilbert — COMMENTED** [review]
This worked great for me!

**Comment by miek** [comment]
Thanks for spotting that and for the PR!

In testing I've noticed another problem though: if you load a sigmf file then load a raw file, the annotations still show up. The `clear` call should probably move to `InputSource::openFile` just before the metadata reading.

**Comment by devnulling** [comment]
@miek good catch. This is updated to put the .clear() in then openFile call. 

Are you able to squash the commits on the merge? if not I can find my ssh key :)

**Comment by miek** [comment]
Thanks!

**Pull request merged**
